(* generated by dune *)

(** @canonical Engine_interface.Boundary_classifier *)
module Boundary_classifier = Engine_interface__Boundary_classifier

(** @canonical Engine_interface.Domain_manager *)
module Domain_manager = Engine_interface__Domain_manager
